// public/etaxtrain-main/src/components/QuizRecall.tsx
import React, { useState } from 'react';
import {
  HelpCircle,
  CheckCircle2,
  XCircle,
  RotateCw,
  Sparkles,
  Award,
  Brain,
  ShieldCheck,
  ArrowRight,
  BookOpen,
} from 'lucide-react';
import { FLASHCARDS_DATA } from '../data/manualData';
import { CardProgress, SM2Rating } from '../types';
import { processSM2Review } from '../lib/sm2';

interface QuizRecallProps {
  cardProgressMap: Record<string, CardProgress>;
  onSaveReview: (cardId: string, newProgress: CardProgress, rating: SM2Rating) => void;
  onGoToManualPage: (pageNumber: number) => void;
}

export const QuizRecall: React.FC<QuizRecallProps> = ({
  cardProgressMap,
  onSaveReview,
  onGoToManualPage,
}) => {
  const [currentQuizIndex, setCurrentQuizIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [score, setScore] = useState(0);

  // Shuffle or slice 10 quiz cards
  const quizCards = FLASHCARDS_DATA.slice(0, 15);
  const currentCard = quizCards[currentQuizIndex];

  if (!currentCard || currentQuizIndex >= quizCards.length) {
    return (
      <div className="max-w-2xl mx-auto p-8 space-y-6 text-center bg-white rounded-2xl border border-slate-200 shadow-sm my-8 text-slate-900">
        <div className="w-16 h-16 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center mx-auto border border-indigo-200">
          <Award className="w-10 h-10" />
        </div>

        <div className="space-y-2">
          <h2 className="text-2xl font-extrabold text-slate-900">Quiz Challenge Complete!</h2>
          <p className="text-slate-600 text-sm">
            You scored <strong className="text-emerald-700">{score} out of {quizCards.length}</strong> on verbatim recall testing!
          </p>
        </div>

        <button
          onClick={() => {
            setCurrentQuizIndex(0);
            setScore(0);
            setSelectedOption(null);
            setIsSubmitted(false);
          }}
          className="w-full py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl shadow-sm transition-all text-xs"
        >
          Restart Quiz Challenge
        </button>
      </div>
    );
  }

  // Generate 4 multiple choice options: 1 exact correct text, 3 distractors from other cards
  const generateOptions = () => {
    const correct = currentCard.exactAnswerText;
    const distractors = FLASHCARDS_DATA.filter((c) => c.id !== currentCard.id)
      .map((c) => c.exactAnswerText)
      .slice(0, 3);

    const all = [correct, ...distractors];
    // Deterministic pseudo-shuffle based on card ID
    all.sort((a, b) => (a.length % 2 === 0 ? 1 : -1));
    return all;
  };

  const options = generateOptions();

  const handleOptionSelect = (opt: string) => {
    if (isSubmitted) return;
    setSelectedOption(opt);
  };

  const handleSubmit = () => {
    if (!selectedOption) return;
    setIsSubmitted(true);

    const isCorrect = selectedOption === currentCard.exactAnswerText;
    if (isCorrect) {
      setScore((prev) => prev + 1);
    }

    // Update SM-2 score (Rating 3 if correct, Rating 1 if wrong)
    const rating: SM2Rating = isCorrect ? 3 : 1;
    const prog = cardProgressMap[currentCard.id] || {
      cardId: currentCard.id,
      interval: 1,
      repetitionCount: 0,
      easeFactor: 2.5,
      lastReviewedAt: null,
      nextReviewAt: new Date().toISOString(),
      stability: 1,
      state: 'new',
      history: [],
    };

    const updated = processSM2Review(prog, rating);
    onSaveReview(currentCard.id, updated, rating);
  };

  const handleNext = () => {
    setSelectedOption(null);
    setIsSubmitted(false);
    setCurrentQuizIndex((prev) => prev + 1);
  };

  return (
    <div className="max-w-3xl mx-auto p-4 sm:p-6 lg:p-8 space-y-6 text-slate-900">
      {/* Header */}
      <div className="flex items-center justify-between text-xs text-slate-600 font-bold bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
        <span className="flex items-center space-x-2 text-indigo-600">
          <HelpCircle className="w-4 h-4" />
          <span>Verbatim Active Recall Quiz</span>
        </span>
        <span className="text-slate-700 font-mono">
          Question {currentQuizIndex + 1} of {quizCards.length} • Score: {score}
        </span>
      </div>

      {/* Main Quiz Box */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 sm:p-8 space-y-6">
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-indigo-700 bg-indigo-50 px-2.5 py-1 rounded-full border border-indigo-200">
              Manual Page {currentCard.pageNumber}
            </span>
            <button
              onClick={() => onGoToManualPage(currentCard.pageNumber)}
              className="text-xs text-slate-500 hover:text-indigo-600 font-bold underline flex items-center space-x-1"
            >
              <BookOpen className="w-3.5 h-3.5" />
              <span>Inspect Source Text</span>
            </button>
          </div>

          <h2 className="text-xl font-extrabold text-slate-900 leading-snug">
            {currentCard.prompt}
          </h2>
        </div>

        {/* Options */}
        <div className="space-y-3">
          {options.map((option, idx) => {
            const isSelected = selectedOption === option;
            const isCorrect = option === currentCard.exactAnswerText;

            let optionStyle = 'bg-slate-50 border-slate-200 hover:border-indigo-500 text-slate-800';

            if (isSubmitted) {
              if (isCorrect) {
                optionStyle = 'bg-emerald-50 border-emerald-500 text-emerald-900 font-medium';
              } else if (isSelected && !isCorrect) {
                optionStyle = 'bg-rose-50 border-rose-500 text-rose-900 font-medium';
              } else {
                optionStyle = 'bg-slate-50 border-slate-200 text-slate-400 opacity-60';
              }
            } else if (isSelected) {
              optionStyle = 'bg-indigo-50 border-indigo-600 text-indigo-900 font-medium shadow-sm';
            }

            return (
              <div
                key={idx}
                onClick={() => handleOptionSelect(option)}
                className={`p-4 rounded-xl border cursor-pointer transition-all duration-200 flex items-start space-x-3 text-xs leading-relaxed ${optionStyle}`}
              >
                <span className="w-5 h-5 rounded-full bg-white border border-slate-300 flex items-center justify-center font-bold shrink-0 mt-0.5 text-slate-700">
                  {String.fromCharCode(65 + idx)}
                </span>
                <span className="flex-1 font-sans font-medium text-slate-900">{option}</span>
                {isSubmitted && isCorrect && <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />}
                {isSubmitted && isSelected && !isCorrect && <XCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />}
              </div>
            );
          })}
        </div>

        {/* Controls */}
        <div className="pt-4 border-t border-slate-100 flex justify-between items-center">
          {!isSubmitted ? (
            <button
              onClick={handleSubmit}
              disabled={!selectedOption}
              className={`w-full py-3 rounded-xl font-bold text-xs transition-all ${
                selectedOption
                  ? 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm'
                  : 'bg-slate-100 text-slate-400 cursor-not-allowed border border-slate-200'
              }`}
            >
              Check Answer
            </button>
          ) : (
            <button
              onClick={handleNext}
              className="w-full py-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs transition-all flex items-center justify-center space-x-2 shadow-sm"
            >
              <span>Next Question</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

// resources/js/Pages/Training/Partials/QuizRecall.vue
﻿<script setup>
import { ref, computed } from 'vue';
const props = defineProps({ flashcards: Array, progressMap: Object, isDark: Boolean });
const emit  = defineEmits(['save-review', 'go-to-page']);

const quizCards    = computed(() => props.flashcards.slice(0, 15));
const currentIndex = ref(0);
const selected     = ref(null);
const submitted    = ref(false);
const score        = ref(0);

const card = computed(() => quizCards.value[currentIndex.value]);

const options = computed(() => {
    if (!card.value) return [];
    const correct     = card.value.exact_answer_text;
    const distractors = props.flashcards.filter(c => c.card_key !== card.value.card_key).map(c => c.exact_answer_text).slice(0, 3);
    const all         = [correct, ...distractors];
    all.sort((a, b) => (a.length % 2 === 0 ? 1 : -1));
    return all;
});

function submit() {
    if (!selected.value || !card.value) return;
    submitted.value = true;
    const correct = selected.value === card.value.exact_answer_text;
    if (correct) score.value++;
    emit('save-review', card.value.card_key, correct ? 3 : 1);
}

function next() { selected.value = null; submitted.value = false; currentIndex.value++; }
function restart() { currentIndex.value=0; score.value=0; selected.value=null; submitted.value=false; }

function optStyle(opt) {
    if (!submitted.value) return selected.value===opt
        ? 'bg-teal-50 border-teal-600 text-teal-900 font-medium'
        : 'bg-slate-50 border-slate-200 hover:border-teal-500 text-slate-800';
    if (opt===card.value.exact_answer_text) return 'bg-emerald-50 border-emerald-500 text-emerald-900 font-medium';
    if (opt===selected.value) return 'bg-rose-50 border-rose-500 text-rose-900 font-medium';
    return 'bg-slate-50 border-slate-200 text-slate-400 opacity-60';
}
</script>

<template>
<div class="max-w-3xl mx-auto space-y-6">
    <div v-if="!card || currentIndex >= quizCards.length"
        class="text-center py-12 rounded-2xl border p-8 space-y-5"
        :class="isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-slate-200'">
        <div class="text-5xl">🏆</div>
        <h2 class="text-2xl font-extrabold" :class="isDark ? 'text-white' : 'text-slate-900'">Quiz Complete!</h2>
        <p class="text-sm" :class="isDark ? 'text-gray-300' : 'text-slate-600'">Score: <strong class="text-emerald-600">{{ score }} / {{ quizCards.length }}</strong></p>
        <button @click="restart" class="px-6 py-2.5 text-white font-bold rounded-xl text-sm hover:opacity-90 transition-all" style="background:linear-gradient(135deg,#006970,#00a9b4)">
            Restart Quiz
        </button>
    </div>

    <template v-else>
        <div class="flex items-center justify-between text-xs font-bold p-4 rounded-xl border"
            :class="isDark ? 'bg-gray-800 border-gray-700 text-gray-300' : 'bg-white border-slate-200 text-slate-600'">
            <span>❓ Verbatim Active Recall Quiz</span>
            <span>Question {{ currentIndex+1 }} of {{ quizCards.length }} • Score: {{ score }}</span>
        </div>

        <div class="rounded-2xl border p-6 sm:p-8 space-y-6" :class="isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-slate-200'">
            <div class="space-y-2">
                <div class="flex items-center justify-between">
                    <span class="text-xs font-bold bg-teal-50 text-teal-700 border border-teal-200 px-2.5 py-1 rounded-full">Manual Page {{ card.page_number }}</span>
                    <button @click="emit('go-to-page', card.page_number)" class="text-xs text-slate-500 hover:text-teal-600 font-bold underline">📖 Inspect Source</button>
                </div>
                <h2 class="text-xl font-extrabold leading-snug" :class="isDark ? 'text-white' : 'text-slate-900'">{{ card.prompt }}</h2>
            </div>

            <div class="space-y-3">
                <div v-for="(opt, idx) in options" :key="idx"
                    @click="!submitted && (selected = opt)"
                    class="p-3.5 rounded-xl border cursor-pointer transition-all text-xs leading-relaxed flex items-start gap-2.5"
                    :class="optStyle(opt)">
                    <span class="w-5 h-5 rounded-full bg-white border border-slate-300 flex items-center justify-center font-bold text-slate-700 text-[10px] shrink-0 mt-0.5">{{ String.fromCharCode(65+idx) }}</span>
                    <span class="flex-1 font-medium">{{ opt }}</span>
                    <span v-if="submitted && opt===card.exact_answer_text">✅</span>
                    <span v-else-if="submitted && opt===selected">❌</span>
                </div>
            </div>

            <div class="pt-4 border-t" :class="isDark ? 'border-gray-700' : 'border-slate-100'">
                <button v-if="!submitted" @click="submit" :disabled="!selected"
                    class="w-full py-2.5 rounded-xl font-bold text-xs transition-all"
                    :class="selected ? 'text-white hover:opacity-90' : 'bg-slate-100 text-slate-400 cursor-not-allowed border border-slate-200'"
                    :style="selected ? 'background:linear-gradient(135deg,#006970,#00a9b4)' : ''">
                    Check Answer
                </button>
                <button v-else @click="next" class="w-full py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs">
                    Next Question →
                </button>
            </div>
        </div>
    </template>
</div>
</template>
